### ISSUE TITLE
Fix FR lang button on News page

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/midisWP#2]

**Comment by rayrshah** [comment]
https://www.figma.com/file/oH0sJGfswfMBtm4aenKOl4?node-id=1624:6#85362248

**Comment by adambard1** [comment]
This FR language button does not work, it takes you to the first article (in this case https://midisgroup.thinkdesign.com/liveroute-has-earned-modernization-of-web-applications-to-microsoft-azure-advanced-specialization/)
However, if you are on another FR page, clicking the Header menu "Actualités" does get us to the FR NEws page, so the issue is with the button, not the page.

**Comment by adambard1** [comment]
@ajazmi just checking that this issue is accessible to you.

**Comment by adambard1** [comment]
This is fixed
