### ISSUE TITLE
Provide technical expectations to Midis, to enable best hosting plan

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#52]
send by email to Ray to forward.

**Comment by seovalleygit** [comment]
@ajazmi @adam-td 

Technical Requirements

Linux Server Enviroment
PHP: 7.4
MYSQL: 5.6
Apache/NGINX Web Server
Disk Space: Minimum 10 GB
Hosting Should Support Custom Wordpress Installation (Some managed hosting providers like WPEngine do not support this feature because they run their own customized wordpress version. Please make sure with support before purchase).

**Comment by rayrshah** [comment]
I will advise GoDaddy Grow @seovalleygit.  IS this OK? 

![image](https://user-images.githubusercontent.com/2479135/127156111-cc866d04-8d1e-4dbc-b8d8-5e1c23fe5e65.png)

**Comment by seovalleygit** [comment]
@adam-td @ajazmi GoDaddy Grow plan is fine.

**Comment by adam-td** [comment]
Leaving this open so we can see info, but adding Done label
