### ISSUE TITLE
Affiliate in Africa and Middle East region, info tile not stable for Middle East region – disappears from view after a few seconds

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#56]
A [new affiliate was created](https://midisgroup.thinkdesign.com/affiliate/adam-test-affiliate/) with Africa and Middle East selected as its regions.

On the front end, the Affiliate appears in the Affiliate Directory in Africa region but the Middle East tile disappears after a few seconds. It reappears and disappears again on refresh. This affiliate was duplicated from EN to FR, and the issue happens on both EN and FR sites.

**This may be a non-problem if any affiliate can only have one region. Midis to confirm.**

- However, since multiple select is possible in the region widget, it should work nonetheless.
<img width="294" alt="Screen Shot 2021-07-29 at 10 09 16" src="https://user-images.githubusercontent.com/87426372/127506915-d72c5146-d25f-4da6-9b10-5dc042fe8dd3.png">

See the video here to see the tile appear and disappear.

https://user-images.githubusercontent.com/87426372/127506456-fd7a3750-9f6e-4504-ac09-55bb07a8dff8.mov

**Comment by seovalleygit** [comment]
@adam-td @ajazmi This is happening because of the filter script. This is how it was on the current site. Script hides duplicate instances once initialize that is the reason it appears for a while in the start. This means an affiliate can belong to one region at a time. The second copy of the affiliate needs to create if it needs to showcase that affiliate in other regions. The same we are doing for other affiliates like iStyle, MDS. To avoid confusion I changed the region appearance to a radio button so only one can be selected at a time.

![image](https://user-images.githubusercontent.com/86654942/127735489-f8403fa1-d722-49b1-be18-742c06ed9543.png)
