### ISSUE TITLE
test.midisgroup.com is  broken

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/midisWP#63]
![image](https://user-images.githubusercontent.com/2479135/131346842-fa77e5fb-6e47-43bf-ad4f-6e630aabe2d5.png)
![image](https://user-images.githubusercontent.com/2479135/131346874-eb9e9df6-83a1-4f8d-ab01-2bd3265d77bc.png)

**Comment by seovalleygit** [comment]
@rayrshah @adam-td @ajazmi 

Hello Ray,

This issue is related to the Godaddy server. As the error itself indicate "SSL Handshake Failed". Some SSL errors occurred when CloudFlare cache servers were not able to connect with GoDaddy server. 

This article describes possible reasons for this error to happen. You can report it to Godaddy support if required or it occur again in the future.

https://kinsta.com/knowledgebase/ssl-handshake-failed/
